"""empty message

Revision ID: 14d4df3b00db
Revises: a7a13fe51874
Create Date: 2023-05-05 12:59:06.301518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d4df3b00db'
down_revision = 'a7a13fe51874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_name'), ['name'], unique=True)

    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_key'))

    op.drop_table('version')
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_name'))

    op.drop_table('app')
    # ### end Alembic commands ###
