"""empty message

Revision ID: 30ca7bb1b8ea
Revises: bb361f3006ae
Create Date: 2023-03-24 10:36:02.787012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ca7bb1b8ea'
down_revision = 'bb361f3006ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceName', sa.String(length=140), nullable=True),
    sa.Column('currentUsername', sa.String(length=140), nullable=True),
    sa.Column('serialNumber', sa.String(length=140), nullable=True),
    sa.Column('localIp', sa.String(length=140), nullable=True),
    sa.Column('systemModel', sa.String(length=140), nullable=True),
    sa.Column('systemManufacturer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_timestamp'))

    op.drop_table('request')
    # ### end Alembic commands ###
