"""no sotring data

Revision ID: 5cdaf532e744
Revises: a1a54e64e094
Create Date: 2023-04-02 16:45:19.504690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdaf532e744'
down_revision = 'a1a54e64e094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index('ix_request_timestamp')

    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deviceName', sa.VARCHAR(length=140), nullable=True),
    sa.Column('serialNumber', sa.VARCHAR(length=140), nullable=True),
    sa.Column('localIp', sa.VARCHAR(length=140), nullable=True),
    sa.Column('systemModel', sa.VARCHAR(length=140), nullable=True),
    sa.Column('systemManufacturer', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=140), nullable=True),
    sa.Column('keyTypeUsed', sa.VARCHAR(length=140), nullable=True),
    sa.Column('macAddress', sa.VARCHAR(length=140), nullable=True),
    sa.Column('cortex', sa.VARCHAR(length=140), nullable=True),
    sa.Column('insightVM', sa.VARCHAR(length=140), nullable=True),
    sa.Column('lastConnected', sa.VARCHAR(length=140), nullable=True),
    sa.Column('freeSpace', sa.VARCHAR(length=140), nullable=True),
    sa.Column('citrixVersion', sa.VARCHAR(length=140), nullable=True),
    sa.Column('bitLockKey', sa.VARCHAR(length=140), nullable=True),
    sa.Column('osLevel', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index('ix_request_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
