"""empty message

Revision ID: 703e9e6fd640
Revises: 14d4df3b00db
Create Date: 2023-05-26 09:32:09.655848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703e9e6fd640'
down_revision = '14d4df3b00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fake_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('true_key', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_version_key')
        batch_op.create_index(batch_op.f('ix_version_fake_key'), ['fake_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_version_true_key'), ['true_key'], unique=True)
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_version_true_key'))
        batch_op.drop_index(batch_op.f('ix_version_fake_key'))
        batch_op.create_index('ix_version_key', ['key'], unique=False)
        batch_op.drop_column('true_key')
        batch_op.drop_column('fake_key')

    # ### end Alembic commands ###
