"""empty message

Revision ID: 7bf214d70fb3
Revises: 30ca7bb1b8ea
Create Date: 2023-03-24 12:34:23.521234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf214d70fb3'
down_revision = '30ca7bb1b8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=140), nullable=True))
        batch_op.drop_column('currentUsername')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentUsername', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
