"""empty message

Revision ID: 8a6d9294bcbe
Revises: 7bf214d70fb3
Create Date: 2023-03-24 14:43:56.800188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6d9294bcbe'
down_revision = '7bf214d70fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyTypeUsed', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('keyTypeUsed')

    # ### end Alembic commands ###
