"""added columns

Revision ID: a1a54e64e094
Revises: 8a6d9294bcbe
Create Date: 2023-04-02 12:30:54.103279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a54e64e094'
down_revision = '8a6d9294bcbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('macAddress', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('cortex', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('insightVM', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('lastConnected', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('freeSpace', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('citrixVersion', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('bitLockKey', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('osLevel', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('osLevel')
        batch_op.drop_column('bitLockKey')
        batch_op.drop_column('citrixVersion')
        batch_op.drop_column('freeSpace')
        batch_op.drop_column('lastConnected')
        batch_op.drop_column('insightVM')
        batch_op.drop_column('cortex')
        batch_op.drop_column('macAddress')

    # ### end Alembic commands ###
