"""empty message

Revision ID: ae47a9b5d7d1
Revises: 9aeff9d251e2
Create Date: 2023-06-20 14:48:57.549531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47a9b5d7d1'
down_revision = '9aeff9d251e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ad__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('ad_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ad_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('ai__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('ai_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('conf__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conf__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_conf__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_conf__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_conf__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('cs3__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cs3__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs3__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs3__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs3__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('cs4__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cs4__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs4__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs4__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs4__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('cs_bk__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cs_bk__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_bk__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_bk__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_bk__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('cs_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cs_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_cs_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('fac__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fac__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fac__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fac__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fac__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('fac_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fac_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fac_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fac_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fac_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('fi__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fi__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fi__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fi__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fi__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('fi_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fi_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fi_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fi_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fi_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('global__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_global__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_global__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_global__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_global__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('hpo__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hpo__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_hpo__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_hpo__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_hpo__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('hpo_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hpo_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_hpo_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_hpo_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_hpo_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('if__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_if__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_if__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_if__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_if__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('if_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_if_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_if_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_if_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_if_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('it__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_it__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_it__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_it__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_it__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('it_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_it_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_it_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_it_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_it_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('kit__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_kit__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_kit__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_kit__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_kit__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('mc2__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mc2__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc2__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc2__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc2__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('mc3__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mc3__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc3__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc3__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc3__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('mc_bk__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mc_bk__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc_bk__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc_bk__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc_bk__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('mc_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mc_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mc_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('mr__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mr__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('mr_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mr_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_mr_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('nh__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nh__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_nh__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_nh__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_nh__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('nh_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nh_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_nh_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_nh_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_nh_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('off__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_off__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_off__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_off__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_off__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('opto__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_opto__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_opto__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_opto__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_opto__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('opto_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_opto_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_opto_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_opto_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_opto_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pa__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pa__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pa__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pa__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pa__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pa_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pa_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pa_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pa_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pa_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pc3__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pc3__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc3__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc3__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc3__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pc4__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pc4__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc4__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc4__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc4__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pc_bk__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pc_bk__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc_bk__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc_bk__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc_bk__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pc_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pc_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pc_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('ph__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ph__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ph__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ph__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ph__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('ph_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ph_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ph_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ph_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_ph_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('popup__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_popup__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_popup__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_popup__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_popup__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pt__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pt__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('pt_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pt_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('sp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('sp_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sp_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_sp_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('wh__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wh__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('wh_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wh_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wh_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('wl__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wl__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wl__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wl__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wl__viz__data_year_5_count'), ['year_5_count'], unique=False)

    with op.batch_alter_table('wl_lp__viz__data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_3_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_4_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_5_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wl_lp__viz__data_year_2_count'), ['year_2_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wl_lp__viz__data_year_3_count'), ['year_3_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wl_lp__viz__data_year_4_count'), ['year_4_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_wl_lp__viz__data_year_5_count'), ['year_5_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wl_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wl_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_wl_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_wl_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_wl_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('wl__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wl__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_wl__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_wl__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_wl__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('wh_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_wh_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_wh_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_wh_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('wh__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wh__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_wh__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_wh__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_wh__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('sp_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sp_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_sp_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_sp_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_sp_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('sp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_sp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_sp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_sp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pt_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pt_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pt_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pt_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pt_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pt__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pt__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pt__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pt__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pt__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('popup__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_popup__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_popup__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_popup__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_popup__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('ph_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ph_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_ph_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_ph_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_ph_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('ph__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ph__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_ph__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_ph__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_ph__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pc_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pc_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pc_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pc_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pc_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pc_bk__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pc_bk__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pc_bk__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pc_bk__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pc_bk__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pc4__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pc4__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pc4__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pc4__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pc4__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pc3__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pc3__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pc3__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pc3__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pc3__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pa_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pa_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pa_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pa_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pa_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('pa__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pa__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_pa__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_pa__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_pa__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('opto_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opto_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_opto_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_opto_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_opto_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('opto__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opto__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_opto__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_opto__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_opto__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('off__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_off__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_off__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_off__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_off__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('nh_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nh_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_nh_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_nh_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_nh_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('nh__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nh__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_nh__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_nh__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_nh__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('mr_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mr_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_mr_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_mr_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_mr_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('mr__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mr__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_mr__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_mr__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_mr__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('mc_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mc_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_mc_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_mc_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_mc_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('mc_bk__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mc_bk__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_mc_bk__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_mc_bk__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_mc_bk__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('mc3__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mc3__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_mc3__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_mc3__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_mc3__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('mc2__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mc2__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_mc2__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_mc2__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_mc2__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('kit__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kit__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_kit__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_kit__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_kit__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('it_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_it_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_it_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_it_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_it_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('it__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_it__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_it__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_it__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_it__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('if_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_if_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_if_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_if_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_if_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('if__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_if__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_if__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_if__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_if__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('hpo_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hpo_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_hpo_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_hpo_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_hpo_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('hpo__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hpo__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_hpo__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_hpo__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_hpo__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('global__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_global__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_global__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_global__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('fi_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fi_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_fi_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_fi_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_fi_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('fi__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fi__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_fi__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_fi__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_fi__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('fac_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fac_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_fac_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_fac_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_fac_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('fac__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fac__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_fac__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_fac__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_fac__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('cs_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cs_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_cs_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_cs_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_cs_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('cs_bk__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cs_bk__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_cs_bk__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_cs_bk__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_cs_bk__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('cs4__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cs4__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_cs4__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_cs4__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_cs4__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('cs3__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cs3__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_cs3__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_cs3__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_cs3__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('conf__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conf__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_conf__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_conf__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_conf__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('ai_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_ai_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_ai_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_ai_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('ai__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_ai__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_ai__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_ai__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('ad_lp__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_lp__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_ad_lp__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_ad_lp__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_ad_lp__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    with op.batch_alter_table('ad__viz__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad__viz__data_year_5_count'))
        batch_op.drop_index(batch_op.f('ix_ad__viz__data_year_4_count'))
        batch_op.drop_index(batch_op.f('ix_ad__viz__data_year_3_count'))
        batch_op.drop_index(batch_op.f('ix_ad__viz__data_year_2_count'))
        batch_op.drop_column('year_5_count')
        batch_op.drop_column('year_4_count')
        batch_op.drop_column('year_3_count')
        batch_op.drop_column('year_2_count')

    # ### end Alembic commands ###
